llm:
  creative:
    default: gemini
    models:
      gemma:
        base_url: "http://localhost:1234/v1"
        model: "lm_studio/gemma-3-12b-it"
        api_key: "lm_studio"
      quill:
        base_url: "http://localhost:1234/v1"
        model: "lm_studio/quill-v1"
        api_key: "lm_studio"
      mn-12b-lyra-v1:
        base_url: "http://localhost:1234/v1"
        model: "lm_studio/mn-12b-lyra-v1"
        api_key: "lm_studio"
      darkest-muse:
        base_url: "http://localhost:1234/v1"
        model: "lm_studio/darkest-muse-v1"
        api_key: "lm_studio"
      gemini:
        model: "gemini/gemini-2.0-flash"
        api_key: "API key"
      gpt:
        base_url: "http://localhost:1234/v1"
        model: "lm_studio/openai/gpt-oss-20b"
        api_key: "lm_studio"
      qwen:
        base_url: "http://localhost:1234/v1"
        model: "lm_studio/qwen3-14b"
        api_key: "lm_studio"
      qwq:
        base_url: "https://openrouter.ai/api/v1"
        model: "openrouter/arliai/qwq-32b-arliai-rpr-v1:free"
        api_key: "API key"


  evaluation:
    default: gemini
    models:
      gpt:
        base_url: "http://localhost:1234/v1"
        model: "lm_studio/openai/gpt-oss-20b"
        api_key: "lm_studio"
      llama:
        base_url: "http://localhost:1234/v1"
        model: "lm_studio/meta-llama-3.1-8b-instruct"
        api_key: "lm_studio"
      qwen:
        base_url: "http://localhost:1234/v1"
        model: "lm_studio/qwen3-14b"
        api_key: "lm_studio"
      gemini:
        model: "gemini/gemini-2.0-flash"
        api_key: "API key"



llm_parameters:
  creative:
    temperature: 0.8
    top_p: 0.9
    max_completion_tokens: 8192
    presence_penalty: 0.6
    frequency_penalty: 0.4
    stop: ["###"]
  evaluation:
    temperature: 0.0
    top_p: 0.5
    presence_penalty: 0.0
    frequency_penalty: 0.0
    stop: ["###"]
